### ISSUE TITLE
please reduce the frequency of call

### ISSUE THREAD

**Issue by golezi** [serverless-components/tencent-apigateway#12]
应该是因为在一个serverless.yml配置了多个云函数，导致并发太大
目前是添加--debug参数让程序进行打印操作花费一些时间降低并发
希望能提高一下20qps的限制或在sls cli中进行20qps的限制而不是抛出错误
![image](https://user-images.githubusercontent.com/23138658/81517514-cc81d300-936d-11ea-96c0-6eee4f9470b5.png)

**Comment by tinafangkunding** [comment]
收到反馈，看起来是接口的调用频率超限了
